// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukxyytxvmsnmfspowwrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVreHl5dHh2bXNubWZzcG93d3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDMwNzYsImV4cCI6MjA3Mjk3OTA3Nn0.Xm45B8nws0hBgDHdkhevGdeX1PSC8Wm81quqkzFbfZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});